use anyhow::{anyhow, Result};
use candle_core::{DType, Device, Tensor};
use candle_transformers::generation::{LogitsProcessor, Sampling};
use tokenizers::tokenizer::Tokenizer;

use crate::{CandleModelWeights, TensorStreamTrait, TokenOutputStream, TokenStreamTrait, TokenWrapper, TokenizerConfig};

/// The actual asset struct
#[derive(Debug)]
pub struct CandleAsset {
    /// The device for computation
    pub device: Device,
    /// The loaded CandleModelInput
    pub model_weights: CandleModelWeights,
    /// The tokenizer
    pub tokenizer: Tokenizer,
    /// The tokenizer configurations
    pub tokenizer_config: TokenizerConfig,
    /// The default type to use
    pub dtype: DType,
}

impl CandleAsset {
    pub fn convert_vec_to_tensor(&self, input: &TokenWrapper) -> Result<Tensor> {
        match input {
            TokenWrapper::D1(tokens) => {
                let tensor = Tensor::new(tokens.as_slice(), &self.device)?.unsqueeze(0)?;
                Ok(tensor)
            }
            TokenWrapper::D2(tokens) => {
                let tmp: Vec<&[u32]> = tokens.iter().map(|x| x.as_slice()).collect();
                let tensor = Tensor::new(tmp, &self.device)?.contiguous()?;
                Ok(tensor)
            }
        }
    }
}

impl TokenStreamTrait for CandleAsset {
    fn forward(
        &mut self,
        input: &TokenWrapper,
        index_position: usize,
        attention_mask: Option<&TokenWrapper>,
        include_lm_head: bool,
    ) -> Result<Tensor> {
        // Handle the input type
        let input = self.convert_vec_to_tensor(input)?;
        let attention_mask = match attention_mask {
            Some(m) => Some(self.convert_vec_to_tensor(m)?),
            None => None,
        };

        // Run forward inference
        let result: Tensor = match &mut self.model_weights {
            CandleModelWeights::Bert(mw) => {
                let token_type_ids = input.zeros_like()?;
                mw.forward(&input, &token_type_ids, attention_mask.as_ref())?
            }
            CandleModelWeights::QuantizedBert(mw) => {
                let token_type_ids = input.zeros_like()?;
                mw.forward(&input, &token_type_ids, attention_mask.as_ref())?
            }
            CandleModelWeights::QuantizedQwen2(mw) => {
                mw.forward(
                    &input,
                    index_position,
                    attention_mask.as_ref(),
                    include_lm_head,
                )?
                //logits.squeeze(0)? Needed for chat!
            }
            CandleModelWeights::QuantizedLlama(mw) => {
                mw.forward(&input, index_position)?
                //logits.squeeze(0)?
            }
        };
        Ok(result)
    }

    fn get_tokenizer(&self) -> &Tokenizer {
        &self.tokenizer
    }

    fn get_tokenizer_config(&self) -> &TokenizerConfig {
        &self.tokenizer_config
    }
}

impl TensorStreamTrait for CandleAsset {
    fn get_device(&self) -> &Device {
        &self.device
    }
}

pub fn process_logits_sampler(
    temperature: f64,
    seed: u64,
    top_k: Option<usize>,
    top_p: Option<f64>,
) -> LogitsProcessor {
    let sampling = if temperature <= 0. {
        Sampling::ArgMax
    } else {
        match (top_k, top_p) {
            (None, None) => Sampling::All { temperature },
            (Some(k), None) => Sampling::TopK { k, temperature },
            (None, Some(p)) => Sampling::TopP { p, temperature },
            (Some(k), Some(p)) => Sampling::TopKThenTopP { k, p, temperature },
        }
    };
    LogitsProcessor::from_sampling(seed, sampling)
}

/**
Return the prompt tokens optionally shortening to the maximum input length

# Arguments

* `prompt` - String of the chat prompt generated by `create_prompt_chat`
* `tokenizer` - Tokenizer to use for generating the tokens
* `sample_len` - usize of the number of samples for chat generation
* `max_seq_length` - Optional usize of the maximum input length

# Returns

* `prompt_tokens` - `Vec<usize>` of the number of samples for chat generation
* `to_sample` - `usize` of the number of samples for chat generation
* `tos` - `TokenOutputStream` for use in `stream_chat`

*/
pub fn process_prompt_chat(
    prompt: String,
    tokenizer: &Tokenizer,
    sample_len: usize,
    max_seq_length: Option<usize>,
) -> anyhow::Result<(Vec<u32>, usize, TokenOutputStream)> {
    let tos = TokenOutputStream::new(tokenizer.clone());

    let tokens = tos
        .tokenizer()
        .encode(prompt, true)
        .map_err(anyhow::Error::msg)?;
    let to_sample = sample_len.saturating_sub(1);

    let prompt_tokens = tokens.get_ids();

    let prompt_tokens = match max_seq_length {
        Some(msl) => {
            if prompt_tokens.len() + to_sample > msl - 10 {
                let to_remove = prompt_tokens.len() + to_sample + 10 - msl;
                if to_remove > prompt_tokens.len() {
                    return Err(anyhow!(
                        "The prompt size is {}, the sample size is {}, the maximum allowable sequence length is {}, and the remove length is {} which is greater than the prompt size!",
                        prompt_tokens.len(),
                        to_sample,
                        msl,
                        to_remove
                    ));
                }
                prompt_tokens[prompt_tokens.len().saturating_sub(to_remove)..].to_vec()
            } else {
                prompt_tokens.to_vec()
            }
        }
        None => prompt_tokens.to_vec(),
    };

    Ok((prompt_tokens, to_sample, tos))
}

#[cfg(test)]
mod tests {
    use phymes_data::device;

    use crate::{AvailableCandleAssets, CandleChatConfig, load_model_asset_path, load_tokenizer};

    use super::*;

    #[test]
    fn process_prompt_chat_test() {
        let prompt = "<|im_start|>system\nYou are an expert AI assistant. You are given a question, a set of possible functions/tools, and a set of possible documents. \nBased on the question, you may need to make one or more function/tool calls to achieve the purpose.\nIf none of the functions/tools can be used, point it out. \nIf the given question lacks the parameters required by the function/tool, also point it out.\n\nYou have access to the following tools:\n<tools>[{\"name\":\"multiply\",\"description\":\"A function that multiplies two numbers\",\"parameters\":{\"properties\":{\"x\":{\"description\":\"The first number to multiply\",\"type\":\"number\"},\"y\":{\"description\":\"The second number to multiply\",\"type\":\"number\"}},\"required\":[\"x\",\"y\"],\"type\":\"object\"}}]</tools>\n\nGiven the context information and not prior knowledge, answer the question and provide citations from the documents.\nIf none of the documents are required to answer the question, point it out. \n\nYou have access to the following documents:\n<documents>[{\"title\":\"Title\",\"text\":\"The super informative document\"}]</documents><|im_end|>\n<|im_start|>user\nMultiply 2 by 2.<|im_end|>\n<|im_start|>assistant\n2 x 2 = 4<|im_end|>\n<|im_start|>assistant\n".to_string();

        let path: Option<String> = Some(format!(
            "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/tokenizer.json",
            std::env::var("HOME").unwrap_or("".to_string())
        ));
        let repo = "sentence-transformers/all-MiniLM-L6-v2".to_string();
        let filename = "tokenizer.json".to_string();
        let revision = "main".to_string();
        let max_seq_length: Option<usize> = Some(2048);

        let tokenizer = load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
            .expect("Tokenizer failed to load!");
        if let Ok((tokens, _, _)) =
            process_prompt_chat(prompt.clone(), &tokenizer, 1000, max_seq_length)
        {
            let tokens_expected: Vec<u32> = vec![
                101, 1026, 1064, 10047, 1035, 2707, 1064, 1028, 2291, 2017, 2024, 2019, 6739, 9932,
                3353, 1012, 2017, 2024, 2445, 1037, 3160, 1010, 1037, 2275, 1997, 2825, 4972, 1013,
                5906, 1010, 1998, 1037, 2275, 1997, 2825, 5491, 1012, 2241, 2006, 1996, 3160, 1010,
                2017, 2089, 2342, 2000, 2191, 2028, 2030, 2062, 3853, 1013, 6994, 4455, 2000, 6162,
                1996, 3800, 1012, 2065, 3904, 1997, 1996, 4972, 1013, 5906, 2064, 2022, 2109, 1010,
                2391, 2009, 2041, 1012, 2065, 1996, 2445, 3160, 14087, 1996, 11709, 3223, 2011,
                1996, 3853, 1013, 6994, 1010, 2036, 2391, 2009, 2041, 1012, 2017, 2031, 3229, 2000,
                1996, 2206, 5906, 1024, 1026, 5906, 1028, 1031, 1063, 1000, 2171, 1000, 1024, 1000,
                4800, 22086, 1000, 1010, 1000, 6412, 1000, 1024, 1000, 1037, 3853, 2008, 4800,
                24759, 3111, 2048, 102,
            ];
            assert_eq!(tokens, tokens_expected);
        }

        let max_seq_length: Option<usize> = Some(1128);
        let tokenizer = load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
            .expect("Tokenizer failed to load!");
        if let Ok((tokens, _, _)) =
            process_prompt_chat(prompt.clone(), &tokenizer, 1000, max_seq_length)
        {
            let tokens_expected: Vec<u32> =
                vec![1000, 1037, 3853, 2008, 4800, 24759, 3111, 2048, 102];
            assert_eq!(tokens, tokens_expected);
        }

        let max_seq_length: Option<usize> = Some(50);
        let tokenizer = load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
            .expect("Tokenizer failed to load!");
        let error = process_prompt_chat(prompt.clone(), &tokenizer, 1000, max_seq_length);
        assert!(error.is_err());
    }

    #[test]
    fn test_build_candle_chat_asset() {
        // Setup the candle chat config
        let config = CandleChatConfig {
            messages: "messages".to_string(),
            max_tokens: 1000,
            temperature: 0.8,
            seed: 299792458,
            repeat_penalty: 1.1,
            repeat_last_n: 64,
            weights_config_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/config.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            weights_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/smollm2-135m-instruct-q4_k_m.gguf",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            tokenizer_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/tokenizer.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            tokenizer_config_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/tokenizer_config.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            candle_asset: Some(AvailableCandleAssets::SmolLM2_135MChat),
            ..Default::default()
        };

        // Build the asset
        let device = device(config.cpu).unwrap();
        let asset = config
            .candle_asset
            .unwrap()
            .build(
                config.weights_config_file.clone(),
                config.tokenizer_file.clone(),
                config.weights_file.clone(),
                config.tokenizer_config_file.clone(),
                DType::F32,
                device,
            )
            .unwrap();

        // Check the asset
        assert_eq!(asset.tokenizer_config.eos_token_id.unwrap(), 2);
        assert!(asset.tokenizer.to_string(false).is_ok());
        assert_eq!(asset.dtype.as_str(), "f32");
    }
}