use std::sync::Arc;

use anyhow::{Error, Result, anyhow};
use arrow::{
    array::{ArrayRef, Float32Builder, ListBuilder, StringArray},
    datatypes::{DataType, Field},
    record_batch::RecordBatch,
};
use candle_core::{DType, Device, Tensor};
use candle_transformers::generation::{LogitsProcessor, Sampling};
use tokenizers::{PaddingDirection, PaddingParams, PaddingStrategy, Tokenizer};

use crate::{CandleModelWeights, TensorStreamTrait, TokenOutputStream, TokenStreamTrait, TokenWrapper, TokenizerConfig};

/// The actual asset struct
#[derive(Debug)]
pub struct CandleAsset {
    /// The device for computation
    pub device: Device,
    /// The loaded CandleModelInput
    pub model_weights: CandleModelWeights,
    /// The tokenizer
    pub tokenizer: Tokenizer,
    /// The tokenizer configurations
    pub tokenizer_config: TokenizerConfig,
    /// The default type to use
    pub dtype: DType,
}

impl CandleAsset {
    pub fn convert_vec_to_tensor(&self, input: &TokenWrapper) -> Result<Tensor> {
        match input {
            TokenWrapper::D1(tokens) => {
                let tensor = Tensor::new(tokens.as_slice(), &self.device)?.unsqueeze(0)?;
                Ok(tensor)
            }
            TokenWrapper::D2(tokens) => {
                let tmp: Vec<&[u32]> = tokens.iter().map(|x| x.as_slice()).collect();
                let tensor = Tensor::new(tmp, &self.device)?.contiguous()?;
                Ok(tensor)
            }
        }
    }
}

impl TokenStreamTrait for CandleAsset {
    fn forward(
        &mut self,
        input: &TokenWrapper,
        index_position: usize,
        attention_mask: Option<&TokenWrapper>,
        include_lm_head: bool,
    ) -> Result<Tensor> {
        // Handle the input type
        let input = self.convert_vec_to_tensor(input)?;
        let attention_mask = match attention_mask {
            Some(m) => Some(self.convert_vec_to_tensor(m)?),
            None => None,
        };

        // Run forward inference
        let result: Tensor = match &mut self.model_weights {
            CandleModelWeights::Bert(mw) => {
                let token_type_ids = input.zeros_like()?;
                mw.forward(&input, &token_type_ids, attention_mask.as_ref())?
            }
            CandleModelWeights::QuantizedBert(mw) => {
                let token_type_ids = input.zeros_like()?;
                mw.forward(&input, &token_type_ids, attention_mask.as_ref())?
            }
            CandleModelWeights::QuantizedQwen2(mw) => {
                mw.forward(
                    &input,
                    index_position,
                    attention_mask.as_ref(),
                    include_lm_head,
                )?
                //logits.squeeze(0)? Needed for chat!
            }
            CandleModelWeights::QuantizedLlama(mw) => {
                mw.forward(&input, index_position)?
                //logits.squeeze(0)?
            }
        };
        Ok(result)
    }

    fn get_tokenizer(&self) -> &Tokenizer {
        &self.tokenizer
    }

    fn get_tokenizer_config(&self) -> &TokenizerConfig {
        &self.tokenizer_config
    }
}

impl TensorStreamTrait for CandleAsset {
    fn get_device(&self) -> &Device {
        &self.device
    }
}

pub fn process_logits_sampler(
    temperature: f64,
    seed: u64,
    top_k: Option<usize>,
    top_p: Option<f64>,
) -> LogitsProcessor {
    let sampling = if temperature <= 0. {
        Sampling::ArgMax
    } else {
        match (top_k, top_p) {
            (None, None) => Sampling::All { temperature },
            (Some(k), None) => Sampling::TopK { k, temperature },
            (None, Some(p)) => Sampling::TopP { p, temperature },
            (Some(k), Some(p)) => Sampling::TopKThenTopP { k, p, temperature },
        }
    };
    LogitsProcessor::from_sampling(seed, sampling)
}

/**
Return the prompt tokens optionally shortening to the maximum input length

# Arguments

* `prompt` - String of the chat prompt generated by `create_prompt_chat`
* `tokenizer` - Tokenizer to use for generating the tokens
* `sample_len` - usize of the number of samples for chat generation
* `max_seq_length` - Optional usize of the maximum input length

# Returns

* `prompt_tokens` - `Vec<usize>` of the number of samples for chat generation
* `to_sample` - `usize` of the number of samples for chat generation
* `tos` - `TokenOutputStream` for use in `stream_chat`

*/
pub fn process_prompt_chat(
    prompt: String,
    tokenizer: &Tokenizer,
    sample_len: usize,
    max_seq_length: Option<usize>,
) -> anyhow::Result<(Vec<u32>, usize, TokenOutputStream)> {
    let tos = TokenOutputStream::new(tokenizer.clone());

    let tokens = tos
        .tokenizer()
        .encode(prompt, true)
        .map_err(anyhow::Error::msg)?;
    let to_sample = sample_len.saturating_sub(1);

    let prompt_tokens = tokens.get_ids();

    let prompt_tokens = match max_seq_length {
        Some(msl) => {
            if prompt_tokens.len() + to_sample > msl - 10 {
                let to_remove = prompt_tokens.len() + to_sample + 10 - msl;
                if to_remove > prompt_tokens.len() {
                    return Err(anyhow!(
                        "The prompt size is {}, the sample size is {}, the maximum allowable sequence length is {}, and the remove length is {} which is greater than the prompt size!",
                        prompt_tokens.len(),
                        to_sample,
                        msl,
                        to_remove
                    ));
                }
                prompt_tokens[prompt_tokens.len().saturating_sub(to_remove)..].to_vec()
            } else {
                prompt_tokens.to_vec()
            }
        }
        None => prompt_tokens.to_vec(),
    };

    Ok((prompt_tokens, to_sample, tos))
}

pub fn convert_embedding_vector_to_record_batch(
    embedding_vec: Vec<Vec<f32>>,
    other: Vec<RecordBatch>,
) -> Result<RecordBatch> {
    let n_embedding = embedding_vec.len();
    assert_eq!(
        n_embedding,
        other
            .iter()
            .map(|batch| batch.num_rows())
            .collect::<Vec<_>>()
            .iter()
            .sum::<usize>()
    );

    // Wrap into a record batch
    let value_builder = Float32Builder::new();
    let mut list_builder =
        ListBuilder::new(value_builder).with_field(Field::new_list_field(DataType::Float32, false));
    for values in embedding_vec.into_iter() {
        list_builder.values().append_slice(&values);
        list_builder.append(true);
    }
    let embeddings: ArrayRef = Arc::new(list_builder.finish());

    // Extract out all of the other columns
    let mut batch_vec = Vec::new();
    let columns: Vec<String> = other
        .first()
        .unwrap()
        .schema()
        .fields()
        .iter()
        .filter_map(|field| {
            if (field.name() != "text") & (field.data_type() == &DataType::Utf8) {
                Some(field.name().clone())
            } else {
                None
            }
        })
        .collect();
    for column in columns.iter() {
        let array_vec = other
            .iter()
            .flat_map(|batch| {
                batch
                    .column_by_name(column)
                    .unwrap()
                    .as_any()
                    .downcast_ref::<StringArray>()
                    .unwrap()
                    .iter()
                    .map(|s| s.unwrap_or_default())
                    .collect::<Vec<_>>()
            })
            .collect::<Vec<_>>();
        let array_ref: ArrayRef = Arc::new(StringArray::from(array_vec));
        batch_vec.push((column, array_ref));
    }

    let embeddings_name = "embedding".to_string();
    batch_vec.push((&embeddings_name, embeddings));
    let batch = RecordBatch::try_from_iter(batch_vec)?;
    Ok(batch)
}

pub fn convert_embedding_tensor_to_record_batch(
    embedding: Tensor,
    other: Vec<RecordBatch>,
) -> Result<RecordBatch> {
    // Convert the tensor to a vec of vecs
    let embedding_vec: Vec<Vec<f32>> = embedding.to_vec2()?;
    convert_embedding_vector_to_record_batch(embedding_vec, other)
}

type ProcessPromptEmbedOutput = Vec<Vec<u32>>;
/**
Return the prompt tokens as Tensors optionally shortening to the maximum input length

# Arguments

* `prompts` - `Vec<String>` of the chat prompt generated by `create_prompt_embed`
* `tokenizer` - `Tokenizer` to use for generating the tokens
* `eos_token_id` - `u32` id of the end of sentence token used for padding
* `eos_token` - `&str` literal of the end of sentence token used for padding
* `max_seq_length` - `Optional<usize>` of the maximum input length. Note that this feature is currently not implemented
* `device` - `Device` from Candle used to create the Tensors

# Returns

* `tokens` - `Tensor` of tokens of dimension prompt_length by # of prompts
  Note that the tokens are currently returned directly due to memory borrowing issues
  during the token generation process using `Tokenizer` for batch embeddings
* `masks` - `Tensor` of tokens of dimension prompt_length by # of prompts

*/
pub fn process_prompt_embed(
    prompts: &[String],
    tokenizer: &mut Tokenizer,
    eos_token_id: u32,
    eos_token: &str,
    _max_seq_length: Option<usize>,
) -> anyhow::Result<(ProcessPromptEmbedOutput, ProcessPromptEmbedOutput)> {
    let padding = PaddingParams {
        strategy: PaddingStrategy::BatchLongest,
        direction: PaddingDirection::Left,
        pad_to_multiple_of: None,
        pad_id: eos_token_id,
        pad_type_id: 0,
        pad_token: String::from(eos_token),
    };

    tokenizer.with_padding(Some(padding));
    let encoded = tokenizer
        .encode_batch(prompts.to_vec(), true)
        .map_err(Error::msg)?;
    let tokens: Vec<Vec<u32>> = encoded.iter().map(|x| x.get_ids().to_vec()).collect();
    let mask: Vec<Vec<u32>> = encoded
        .iter()
        .map(|x| x.get_attention_mask().to_vec())
        .collect();

    // let tokens: Vec<u32> = encoded.iter().flat_map(|x| x.get_ids().into_iter().map(|x| *x)).collect();
    // let mask: Vec<u32> = encoded.iter().flat_map(|x| x.get_attention_mask().into_iter().map(|x| *x)).collect();
    // dbg!(&mask);

    // let (tokens, mask) = match max_seq_length {
    //     Some(msl) => {
    //         if tokens.len()  > msl - 10 {
    //             let to_remove = tokens.len() + 10 - msl;
    //             if to_remove > tokens.len() {
    //                 return Err(anyhow!("The prompt size is {}, the maximum allowable sequence length is {}, and the remove length is {} which is greater than the prompt size!",
    //                 tokens.len(), msl, to_remove));
    //             }
    //             (tokens[tokens.len().saturating_sub(to_remove)..].to_vec(),
    //             mask[mask.len().saturating_sub(to_remove)..].to_vec())
    //         } else {
    //             (tokens, mask)
    //         }
    //     },
    //     None => (tokens, mask)
    // };

    Ok((tokens, mask))
}

#[cfg(test)]
mod tests {
    use arrow::array::{Float32Array, ListArray, StringArray};
    use candle_core::Device;
    use phymes_data::device;

    use crate::{AvailableCandleAssets, CandleChatConfig, CandleEmbedConfig, load_model_asset_path, load_tokenizer};

    use super::*;

    #[test]
    fn process_prompt_chat_test() {
        let prompt = "<|im_start|>system\nYou are an expert AI assistant. You are given a question, a set of possible functions/tools, and a set of possible documents. \nBased on the question, you may need to make one or more function/tool calls to achieve the purpose.\nIf none of the functions/tools can be used, point it out. \nIf the given question lacks the parameters required by the function/tool, also point it out.\n\nYou have access to the following tools:\n<tools>[{\"name\":\"multiply\",\"description\":\"A function that multiplies two numbers\",\"parameters\":{\"properties\":{\"x\":{\"description\":\"The first number to multiply\",\"type\":\"number\"},\"y\":{\"description\":\"The second number to multiply\",\"type\":\"number\"}},\"required\":[\"x\",\"y\"],\"type\":\"object\"}}]</tools>\n\nGiven the context information and not prior knowledge, answer the question and provide citations from the documents.\nIf none of the documents are required to answer the question, point it out. \n\nYou have access to the following documents:\n<documents>[{\"title\":\"Title\",\"text\":\"The super informative document\"}]</documents><|im_end|>\n<|im_start|>user\nMultiply 2 by 2.<|im_end|>\n<|im_start|>assistant\n2 x 2 = 4<|im_end|>\n<|im_start|>assistant\n".to_string();

        let path: Option<String> = Some(format!(
            "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/tokenizer.json",
            std::env::var("HOME").unwrap_or("".to_string())
        ));
        let repo = "sentence-transformers/all-MiniLM-L6-v2".to_string();
        let filename = "tokenizer.json".to_string();
        let revision = "main".to_string();
        let max_seq_length: Option<usize> = Some(2048);

        let tokenizer = load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
            .expect("Tokenizer failed to load!");
        if let Ok((tokens, _, _)) =
            process_prompt_chat(prompt.clone(), &tokenizer, 1000, max_seq_length)
        {
            let tokens_expected: Vec<u32> = vec![
                101, 1026, 1064, 10047, 1035, 2707, 1064, 1028, 2291, 2017, 2024, 2019, 6739, 9932,
                3353, 1012, 2017, 2024, 2445, 1037, 3160, 1010, 1037, 2275, 1997, 2825, 4972, 1013,
                5906, 1010, 1998, 1037, 2275, 1997, 2825, 5491, 1012, 2241, 2006, 1996, 3160, 1010,
                2017, 2089, 2342, 2000, 2191, 2028, 2030, 2062, 3853, 1013, 6994, 4455, 2000, 6162,
                1996, 3800, 1012, 2065, 3904, 1997, 1996, 4972, 1013, 5906, 2064, 2022, 2109, 1010,
                2391, 2009, 2041, 1012, 2065, 1996, 2445, 3160, 14087, 1996, 11709, 3223, 2011,
                1996, 3853, 1013, 6994, 1010, 2036, 2391, 2009, 2041, 1012, 2017, 2031, 3229, 2000,
                1996, 2206, 5906, 1024, 1026, 5906, 1028, 1031, 1063, 1000, 2171, 1000, 1024, 1000,
                4800, 22086, 1000, 1010, 1000, 6412, 1000, 1024, 1000, 1037, 3853, 2008, 4800,
                24759, 3111, 2048, 102,
            ];
            assert_eq!(tokens, tokens_expected);
        }

        let max_seq_length: Option<usize> = Some(1128);
        let tokenizer = load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
            .expect("Tokenizer failed to load!");
        if let Ok((tokens, _, _)) =
            process_prompt_chat(prompt.clone(), &tokenizer, 1000, max_seq_length)
        {
            let tokens_expected: Vec<u32> =
                vec![1000, 1037, 3853, 2008, 4800, 24759, 3111, 2048, 102];
            assert_eq!(tokens, tokens_expected);
        }

        let max_seq_length: Option<usize> = Some(50);
        let tokenizer = load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
            .expect("Tokenizer failed to load!");
        let error = process_prompt_chat(prompt.clone(), &tokenizer, 1000, max_seq_length);
        assert!(error.is_err());
    }

    #[test]
    fn test_build_candle_chat_asset() {
        // Setup the candle chat config
        let config = CandleChatConfig {
            messages: "messages".to_string(),
            max_tokens: 1000,
            temperature: 0.8,
            seed: 299792458,
            repeat_penalty: 1.1,
            repeat_last_n: 64,
            weights_config_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/config.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            weights_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/smollm2-135m-instruct-q4_k_m.gguf",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            tokenizer_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/tokenizer.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            tokenizer_config_file: Some(format!(
                "{}/.cache/hf/models--HuggingFaceTB--SmolLM2-135M-Instruct/tokenizer_config.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            candle_asset: Some(AvailableCandleAssets::SmolLM2_135MChat),
            ..Default::default()
        };

        // Build the asset
        let device = device(config.cpu).unwrap();
        let asset = config
            .candle_asset
            .unwrap()
            .build(
                config.weights_config_file.clone(),
                config.tokenizer_file.clone(),
                config.weights_file.clone(),
                config.tokenizer_config_file.clone(),
                DType::F32,
                device,
            )
            .unwrap();

        // Check the asset
        assert_eq!(asset.tokenizer_config.eos_token_id.unwrap(), 2);
        assert!(asset.tokenizer.to_string(false).is_ok());
        assert_eq!(asset.dtype.as_str(), "f32");
    }

    #[test]
    fn test_process_prompt_embed() {
        let prompts: Vec<String> = vec!["As a general guideline, the CDC's average requirement of protein for women ages 19 to 70 is 46 grams per day. But, as you can see from this chart, you'll need to increase that if you're expecting or training for a marathon. Check out the chart below to see how much protein you should be eating each day.<|endoftext|>}".to_string(),
        "Definition of summit for English Language Learners. : 1  the highest point of a mountain : the top of a mountain. : 2  the highest level. : 3  a meeting or series of meetings between the leaders of two or more governments.<|endoftext|>}".to_string()];
        let eos_token: &str = "<|endoftext|>";
        let eos_token_id: u32 = 151643;

        let path: Option<String> = Some(format!(
            "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/tokenizer.json",
            std::env::var("HOME").unwrap_or("".to_string())
        ));
        let repo = "sentence-transformers/all-MiniLM-L6-v2".to_string();
        let filename = "tokenizer.json".to_string();
        let revision = "main".to_string();
        let max_seq_length: Option<usize> = Some(2048);
        let mut tokenizer =
            load_tokenizer(load_model_asset_path(&path, &repo, &filename, &revision))
                .expect("Tokenizer failed to load!");

        if let Ok((tokens, masks)) = process_prompt_embed(
            &prompts,
            &mut tokenizer,
            eos_token_id,
            eos_token,
            max_seq_length,
        ) {
            let tokens_expected: Vec<u32> = vec![101, 2004, 1037];
            let masks_expected: Vec<u32> = vec![1, 1, 1];
            assert_eq!(&tokens[0][0..3], tokens_expected.as_slice());
            assert_eq!(&masks[0][0..3], masks_expected.as_slice());
        }
    }

    #[test]
    fn test_build_candle_embed_asset() {
        // Setup the candle embed config
        let config = CandleEmbedConfig {
            documents: "text".to_string(),
            weights_config_file: Some(format!(
                "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/config.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            weights_file: Some(format!(
                // "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/pytorch_model.bin",
                "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/all-minilm-l6-v2-q8_0.gguf",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            tokenizer_file: Some(format!(
                "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/tokenizer.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            tokenizer_config_file: Some(format!(
                "{}/.cache/hf/models--sentence-transformers--all-MiniLM-L6-v2/tokenizer_config.json",
                std::env::var("HOME").unwrap_or("".to_string())
            )),
            candle_asset: Some(
                // crate::candle_assets::candle_which::WhichCandleAsset::BertEmbed,
                AvailableCandleAssets::QuantizedBertEmbed,
            ),
            ..Default::default()
        };

        // Build the asset
        let device = device(config.cpu).unwrap();
        let asset = config
            .candle_asset
            .unwrap()
            .build(
                config.weights_config_file.clone(),
                config.tokenizer_file.clone(),
                config.weights_file.clone(),
                config.tokenizer_config_file.clone(),
                DType::F32,
                device,
            )
            .unwrap();

        // Check the asset
        assert_eq!(asset.tokenizer_config.eos_token_id.unwrap(), 0);
        assert!(asset.tokenizer.to_string(false).is_ok());
        assert_eq!(asset.dtype.as_str(), "f32");
    }

    #[test]
    fn test_convert_embedding_tensor_to_record_batch() -> Result<()> {
        // Create the embeddings tensor
        let embeddings_vec: Vec<Vec<f32>> = vec![
            vec![0., 1., 2., 3., 4., 5., 6., 7.],
            vec![8., 9., 10., 11., 12., 13., 14., 15.],
            vec![16., 17., 18., 19., 20., 21., 22., 23.],
        ];
        let indices_vec = vec!["1", "2", "3"];
        let indices_ref: ArrayRef = Arc::new(StringArray::from(indices_vec.clone()));
        let batch = RecordBatch::try_from_iter(vec![("index", indices_ref)])?;

        let tensor = Tensor::arange(0f32, 24f32, &Device::Cpu)?.reshape((3, 8))?;
        assert_eq!(tensor.to_vec2::<f32>()?, embeddings_vec);

        // Convert to a record batch
        let batch = convert_embedding_tensor_to_record_batch(tensor, vec![batch])?;
        let indices = batch
            .column_by_name("index")
            .unwrap()
            .as_any()
            .downcast_ref::<StringArray>()
            .unwrap()
            .iter()
            .map(|s| s.unwrap_or_default())
            .collect::<Vec<_>>();
        assert_eq!(indices, indices_vec);
        let embeddings = batch
            .column_by_name("embedding")
            .unwrap()
            .as_any()
            .downcast_ref::<ListArray>()
            .unwrap()
            .iter()
            .map(|s| {
                s.unwrap()
                    .as_any()
                    .downcast_ref::<Float32Array>()
                    .unwrap()
                    .iter()
                    .map(|f| f.unwrap())
                    .collect::<Vec<_>>()
            })
            .collect::<Vec<_>>();
        assert_eq!(embeddings, embeddings_vec);

        Ok(())
    }
}