version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: main
    groups:
      prost:
        applies-to: version-updates
        patterns:
          - "prost*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
