[workspace]
members = [
    "phymes-agents",
    "phymes-ml",
    "phymes-app",
    "phymes-core",
    "phymes-data",
    "phymes-event",
    "phymes-message",
    "phymes-processor",
    "phymes-schemas",
    "phymes-server",
    "phymes-diagnostics"
]
resolver = "3"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[patch.crates-io]
flate2 = { git = "https://github.com/dmccloskey/flate2-rs.git", branch = "fix/wasm32" }
diff-match-patch-rs = { git = "https://github.com/dmccloskey/diff-match-patch-rs.git", branch = "fix/wasm32" }
