[workspace]
members = [
    "phymes-agents",
    "phymes-ml",
    "phymes-app",
    "phymes-core",
    "phymes-data",
    "phymes-server",
    "phymes-diagnostics"
]
resolver = "3"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
