[package]
name = "phymes-diagnostics"
version = "0.3.0"
edition = "2024"
authors = ["Douglas McCloskey"]
description = "The diagnostics tools for debugging and optimizing PHYMES applications"
license = "MIT AND Apache-2.0"
repository = "https://github.com/biom8er/phymes"
documentation = "https://docs.rs/phymes-diagnostics"

[features]
default = ["wsl"]
wasip2 = [] # for compatibility with agents
wsl = [] # for compatibility with agents
hf_hub = [] # for compatibility with agents
api = [] # for compatibility with agents
gpu = [] # for compatibility with agents
candle = [] # for compatibility with agents

[dependencies]
arrow = { workspace = true, features = ["prettyprint"] }
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
parking_lot = { workspace = true }
web-time = "1.1.0"
hashbrown = "0.15.4"
chrono = { workspace = true }
bytes  = { workspace = true }
getrandom = { workspace = true }
