use anyhow::{Result, anyhow};
use clap::{Parser, ValueEnum};
use phymes_core::{MappableTrait, Subject, SubjectTrait};
use phymes_data::DataConfigTrait;
use phymes_diagnostics::HashSet;
use serde::{Deserialize, Serialize};

use crate::candle_assets::AvailableCandleAssets;
use crate::openai_asset::AvailableOpenAIAssets;

#[derive(Debug, ValueEnum, PartialEq, Clone, Eq, Serialize, Deserialize)]
pub enum Pool {
    /// Select the CLS token as embedding
    Cls,
    /// Apply Mean pooling to the model embeddings
    Mean,
    /// Apply SPLADE (Sparse Lexical and Expansion) to the model embeddings.
    /// This option is only available if the loaded model is a `ForMaskedLM` Transformer
    /// model.
    Splade,
    /// Select the last token as embedding
    LastToken,
}

/// Config for text embedding inference (TEI)
///
/// see the NVIDIA NIMs reference <https://docs.nvidia.com/nim/nemo-retriever/text-embedding/latest/reference.html>
/// see the OpenAI reference <https://platform.openai.com/docs/guides/embeddings>
#[derive(Parser, Debug, Serialize, Deserialize, Default, Clone)]
#[command(author, version, about, long_about = None)]
pub struct CandleEmbedConfig {
    /// GGUF file to load, typically a .gguf file generated by the quantize command from llama.cpp
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights_file: Option<String>,

    /// list of queries formatted as a JSON string e.g., "['query1', 'query2']"
    #[arg(long)]
    pub documents: String,

    /// The tokenizer config in json format.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_file: Option<String>,

    /// The model weights config in json format.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights_config_file: Option<String>,

    /// The tokenizer config config file in json format.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_config_file: Option<String>,

    /// The API endpoint for chat completion
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_url: Option<String>,

    /// The number of dimensions the resulting output embeddings should have.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<i32>,

    /// The format to return the embeddings in. Can be either float or base64
    #[arg(long, default_value = "float")]
    pub encoding_format: String,

    /// The mode to use for embedding. Can be either passage or query
    #[arg(long, default_value = "query")]
    pub input_type: String,

    /// The modality to embed. Can be either be text, image, text_image
    #[arg(long, default_value = "text")]
    pub modality: String,

    /// Run on CPU rather than GPU even if a GPU is available.
    #[arg(long)]
    pub cpu: bool,

    /// The model size to use.
    #[arg(long, default_value = "Qwen-v2-1.5b-embed")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub candle_asset: Option<AvailableCandleAssets>,

    /// The model to use.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub openai_asset: Option<AvailableOpenAIAssets>,
}

impl DataConfigTrait for CandleEmbedConfig {
    fn to_example_json(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(&Self::default())
    }
    fn from_table(table: &Subject) -> Result<Self>
    where
        Self: Sized,
    {
        // Check for the required fields
        let column_names = table
            .get_schema()
            .fields()
            .iter()
            .map(|f| f.name().to_string())
            .collect::<HashSet<_>>();
        if !((column_names.contains("candle_asset") || column_names.contains("openai_asset"))
            && column_names.contains("encoding_format")
            && column_names.contains("input_type")
            && column_names.contains("modality")
            && column_names.contains("documents"))
        {
            return Err(anyhow!(
                "Table {} is missing required Field for `candle_asset`, `openai_asset`, `encoding_format`, `input_type`, `documents`, or `modality` in CandleEmbedConfig.",
                table.get_name()
            ));
        }

        // Try to build the config
        match table.to_struct::<CandleEmbedConfig>() {
            Ok(config_vec) => match config_vec.first() {
                Some(config) => Ok(config.to_owned()),
                None => Err(anyhow!(
                    "No config data found for CandleEmbedConfig with subject {}",
                    table.get_name()
                )),
            },
            Err(err) => Err(anyhow!(
                "CandleEmbedConfig could not be built for subject {}. {err}",
                table.get_name()
            )),
        }
    }
}
