name: docs

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

# trigger for all PRs and changes to main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    name: Upload cargo docs
    runs-on: self-hosted #ubuntu-latest
    container:
      image: amd64/rust
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install python dev
        run: |
          apt update
          apt install -y libpython3.11-dev
      - name: Setup Rust toolchain
        uses: ./.github/actions/rust-build-env
      - name: Run cargo doc
        run: |
          cargo doc --document-private-items --no-deps -p phymes-core --features wsl
          cargo doc --document-private-items --no-deps -p phymes-agents --features wsl
          cargo doc --document-private-items --no-deps -p phymes-server --features wsl
          cargo doc --document-private-items --no-deps -p phymes-app
      - name: Fix file permissions for docs
        shell: sh
        run: |
          chmod -c -R +rX "target/doc" |
          while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload cargo docs artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: crate-docs
          path: target/doc