/// Mermaid.js sequenceDiagram jinja2 template
/// 
/// see <https://mermaid.js.org/syntax/sequenceDiagram.html>
/// 
/// # Notes
/// * the <startDate>, <endDate> syntax with tags is used
/// * a horizontal barplot can be generated by setting the <startDate> to `0` and <dateFormat> of `X` and <axisFormat> of `%s`
/// * a traditiona gannt based on timestamps can be generated by setting the <dateFormat> to `s` and leaving the <axisFormat> blank `''`
pub static MERMAID_SEQUENCE_DIAGRAM_TEMPLATE: &'static str = r#"
        sequenceDiagram
    {%- for row in rows %}
            participant {{ row.participant }}@{ "type": "{{ row.type }} }"
    {%- endfor %}
            title "{{ title }}"
            dateFormat {{ dateFormat }}
        {%- if axisFormat %}
            axisFormat {{ axisFormat }}
        {%- endif %}
    {%- for row in rows %}
        {%- if loop.first %}
            section {{ row.section }}
        {%- elif loop.changed(row.section) %}
            section {{ row.section}}
        {%- endif %}
                {{ row.task }}:{{ row.start }}, {{ row.end }}
    {%- endfor %}"#;

pub static MERMAID_SEQUENCE_DIAGRAM_PARTICIPANTS_TEMPLATE: &'static str = r#"{%- for row in rows %}
participant {{ row.participant }}@{ "type": "{{ row.type }}" }
{%- endfor %}"#;

pub static MERMAID_SEQUENCE_DIAGRAM_MESSAGES_TEMPLATE: &'static str = r#"
{%- for row in rows %}
{{ row.subject }}{{ row.type }}{{ row.activation }}{{ row.object }}: {{ row.message }}
{%- endfor %}
            title "{{ title }}"
            dateFormat {{ dateFormat }}
        {%- if axisFormat %}
            axisFormat {{ axisFormat }}
        {%- endif %}
    {%- for row in rows %}
        {%- if loop.first %}
            section {{ row.section }}
        {%- elif loop.changed(row.section) %}
            section {{ row.section}}
        {%- endif %}
                {{ row.task }}:{{ row.start }}, {{ row.end }}
    {%- endfor %}"#;

/// The `table_expression` variable name in `DataConfig`
pub static MERMAID_SEQUENCE_DIAGRAM_TABLE_EXPRESSION: &'static str = "rows";

/// Mermaid.js sequenceDiagram input jinja2 template
/// 
/// # Example
/// 
/// ```rust
/// use phymes_core::table::table_script::TableScript;
/// use phymes_data::jinja2_templates::mermaid_sequenceDiagram::MERMAID_SEQUENCE_DIAGRAM_INPUT;
/// let inputs = serde_json::json!({
///     "title": "chart title",
///     "dateFormat": "X",
///     "axisFormat": "%s",
/// });
/// 
/// let input_string = TableScript::new_from_template(MERMAID_SEQUENCE_DIAGRAM_INPUT.to_string()).apply_template(&inputs).unwrap()
///     .lines()
///     .map(|line| line.trim())
///     .collect::<Vec<&str>>()
///     .join("");
/// ```
pub static MERMAID_SEQUENCE_DIAGRAM_INPUT: &'static str = r#"{
"title": "{{ title }}",
"dateFormat": "{{ dateFormat }}",
"axisFormat": "{{ axisFormat }}"
}"#;

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use anyhow::Result;
    use arrow::array::{ArrayRef, RecordBatch, StringArray, UInt32Array};
    use phymes_core::{session::common_traits::{BuildableTrait, BuilderTrait, MappableTrait}, table::{table_script::TableScript, table_trait::{Table, TableBuilderTrait, TableTrait}}};
    use serde_json::{Map, Value};
    use crate::jinja2_templates::mermaid_html::{MERMAID_HTML_POST, MERMAID_HTML_PRE};

    use super::*;

    #[test]
    fn test_mermaid_sequence_diagram_html() -> Result<()> {
        // Create the dummy data for the participants
        let participant_vec = ["Measurement", "DataAnalysis", "Group1", "Group2", "Group3"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let participant_type_vec = ["collections", "collections", "participant", "participant", "participant"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();

        let participant_arr: ArrayRef = Arc::new(StringArray::from(participant_vec));
        let participant_type_arr: ArrayRef = Arc::new(StringArray::from(participant_type_vec));
        let batch = RecordBatch::try_from_iter(vec![
            ("participant_name", participant_arr),
            ("participant_type", participant_type_arr),
        ])?;
        let table = Table::get_builder()
            .with_name(MERMAID_SEQUENCE_DIAGRAM_TABLE_EXPRESSION)
            .with_record_batches(vec![batch])?
            .build()?;

        // todo!() render the intermediate participants section

        // Create the dummy data for the messages
        let subject_vec = ["Measurement", "DataAnalysis", "DataAnalysis", "DataAnalysis"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let object_vec = ["DataAnalysis", "Group1", "Group2", "Group3"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let message_type_vec = ["->>", "->>", "->>", "->>"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let activation_vec = ["", "+", "", "-"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let message_vec = ["n=4095<br/>n=904 statin users<br/>n=3191 non-statin users", 
            "n=1808<br/>n=904 statin users<br/>n=904 non-statin users", 
            "n=1232<br/>n=616 statin users<br/>n=616 non-statin users", 
            "n=3609<br/>n=762 statin users<br/>n=2845 non-statin users"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let note_vec = ["RFFT<br/>VAT<br/>Statin use<br/>Other variables<br/>FRS<br/>Propensity score", 
            "two sample t-test with equal variance<br/>Mann-Whitney U-test<br/>one-way ANOVA<br/>ANCOVA<br/>regression analysis", 
            "matched on age, sex, education", 
            "matched on FRS score", 
            "comparison based on propensity score"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let note_location_vec = ["left of", "left of", "left of", "left of"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();

        let subject_arr: ArrayRef = Arc::new(StringArray::from(subject_vec));
        let object_arr: ArrayRef = Arc::new(StringArray::from(object_vec));
        let task_arr: ArrayRef = Arc::new(StringArray::from(task_vec));
        let task_arr: ArrayRef = Arc::new(StringArray::from(task_vec));
        let task_arr: ArrayRef = Arc::new(StringArray::from(task_vec));
        let batch = RecordBatch::try_from_iter(vec![
            ("subject_name", subject_arr),
            ("object_name", object_arr),
            ("message_name", start_arr),
            ("message_type", start_arr),
            ("activation_type", start_arr),
            ("message_content", start_arr),
            ("note_content", start_arr),
            ("note_location", end_arr),
        ])?;
        let table = Table::get_builder()
            .with_name(MERMAID_SEQUENCE_DIAGRAM_TABLE_EXPRESSION)
            .with_record_batches(vec![batch])?
            .build()?;

        // Create the input for the template
        let inputs = serde_json::json!({
            "title": "chart title",
            "dateFormat": "X",
            "axisFormat": "%s"
        });
        let input_string = TableScript::new_from_template(MERMAID_SEQUENCE_DIAGRAM_INPUT.to_string()).apply_template(&inputs)?
            .lines()
            .map(|line| line.trim())
            .collect::<Vec<&str>>()
            .join("");

        // Update the input with the dummy chart data
        let mut input_object = serde_json::from_str::<Map<String, Value>>(&input_string)?;
        let _ =  input_object.insert(table.get_name().to_string(), table.to_json_object()?.into());
        let sequence_diagram_template_inputs = serde_json::to_value(input_object)?;

        // Create and render the template with the inputs
        let template = [MERMAID_HTML_PRE, MERMAID_SEQUENCE_DIAGRAM_TEMPLATE, MERMAID_HTML_POST].join("");   
        let script_string = TableScript::new_from_template(template).apply_template(&sequence_diagram_template_inputs)?;

        assert_eq!(
            script_string,
            "<!DOCTYPE html>\n<html>    \n    <head>\n        <meta http-equiv=\"Content-type\" content=\"text/html;charset=UTF-8\">\n        <meta name=\"color-scheme\" content=\"dark light\">\n        <style>\n            @media (prefers-color-scheme: dark) {\n                body {\n                    background-color: black;\n                    color: white;\n                }\n            }\n            @media (prefers-color-scheme: light) {\n                body {\n                    background-color: white;\n                    color: black;\n                }\n            }\n        </style>\n  </head>\n  <body>\n    <pre class=\"mermaid\">\n        sequenceDiagram\n            title \"chart title\"\n            dateFormat X\n            axisFormat %s\n            section Section 1\n                A:0, 7\n            section Section 1\n                B:1, 8\n                C:2, 9\n            section Section 2\n                D:0, 10\n                E:1, 11\n                F:2, 12\n    </pre>\n    <script type=\"module\">\n        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';\n        mermaid.initialize({theme: \"dark\", startOnLoad: true });\n    </script>\n  </body>\n</html>"
        );
        Ok(())
    }
}