[book]
authors = ["dmccloskey"]
language = "en"
src = "src"
title = "phymes-book"

[build]
build-dir = "../target/book"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["./src/assets/mermaid.min.js", "./src/assets/mermaid-init.js"]