[application]

# App (Project) Name
name = "phymes-app"

[web.app]

# HTML title tag content
title = "phymes-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = ["/assets/mermaid.esm.min.mjs"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]