[package]
name = "phymes-data"
version = "0.3.0"
edition = "2024"
authors = ["Douglas McCloskey"]
description = "The data wrangling operators for PHYMES"
license = "MIT AND Apache-2.0"
repository = "https://github.com/biom8er/phymes"
documentation = "https://docs.rs/phymes-data"

[features]
default = ["wsl", "candle"]
accelerate = ["dep:accelerate-src", "candle-core/accelerate"]
mkl = ["dep:intel-mkl-src", "intel-mkl-src/mkl-static-lp64-iomp", "candle-core/mkl"]
mkl-dynamic = ["dep:intel-mkl-src", "intel-mkl-src/mkl-dynamic-lp64-iomp", "candle-core/mkl"]
cuda = ["candle-core/cuda"]
cudnn = ["candle-core/cudnn"]
nccl = ["cuda", "cudarc/nccl"]
wasip2 = ["phymes-subject/wasip2", "phymes-diagnostics/wasip2", "phymes-schemas/wasip2", "lopdf/wasm_js", "dep:quick-xml",
    #"tree-sitter/wasm", DM: issue building for target wasm32-unknown-unknown and wasm32-wasip2 (see open issues on GitHub)
    "dep:regex"]
wsl = ["phymes-subject/wsl", "phymes-diagnostics/wsl", "phymes-schemas/wsl", "lopdf/async", "lopdf/rayon", "quick-xml/tokio", "dep:tempfile", "tree-sitter/std", "dep:tree-sitter-python", "dep:tree-sitter-html", "dep:tree-sitter-rust", "regex/std"]
gpu = ["cuda", "cudnn", "nccl"]
api = ["phymes-subject/api", "phymes-schemas/api", "quick-xml/serialize",]
candle = [] # force use of candle models when api is available

[dependencies]
phymes-diagnostics = { path = "../phymes-diagnostics", default-features = false, optional = true }
phymes-subject = { path = "../phymes-subject", default-features = false, optional = true }
phymes-schemas = { path = "../phymes-schemas", default-features = false, optional = true }
arrow = { version = "58.0.0", default-features = false }
candle-core = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
accelerate-src = { version = "0.3.2", optional = true }
intel-mkl-src = { version = "0.8.1", optional = true }
cudarc = { version = "0.9.14", features = ["f16"], optional = true }
# DM: need to debug the updated version
# Must specify one of the following features: [cuda-version-from-build-system, cuda-12060, cuda-12050, cuda-12040, cuda-12030, cuda-12020, cuda-12010, cuda-12000, cuda-11080, cuda-11070, cuda-11060, cuda-11050, cuda-11040]
# cudarc = { version = "0.12.1", features = ["f16"], optional = true }
serde_json = { workspace = true }
serde = { workspace = true }
bytes  = { workspace = true }
getrandom = { workspace = true }
getrandom_0_2 = { workspace = true }
chrono = { workspace = true }
rayon = { workspace = true }
lopdf = { version = "0.38.0", default-features = false, features = ["rayon"], optional = true }
num-traits = { workspace = true }
quick-xml = { version = "0.39.0", default-features = false, optional = true }
tempfile = { version = "3.25.0", optional = true }
flate2 = { version = "1.1.9" }
diff-match-patch-rs = "0.5.1"
minijinja = { workspace = true }
minijinja-contrib = { workspace = true }
tree-sitter = { version = "0.26.8", default-features = false, optional = true }
tree-sitter-html = { version = "0.23.2", default-features = false, optional = true }
tree-sitter-python = { version = "0.25.0", default-features = false, optional = true }
tree-sitter-rust = { version = "0.23.2", default-features = false, optional = true }
regex = { version = "1.12.3", default-features = false, optional = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "apply_diff"
harness = false
