/// Mermaid.js gantt jinja2 template
///
/// see <https://mermaid.js.org/syntax/gantt.html>
///
/// # Notes
/// * The gantt table MUST be sorted by section!
/// * the `startDate`, `endDate` syntax with tags is used
/// * a horizontal barplot can be generated by setting the `startDate` to `0` and `dateFormat` of `X` and `axisFormat` of `%s`
/// * a traditiona gannt based on timestamps can be generated by setting the `dateFormat` to `x` and leaving the `axisFormat` blank `''`
pub static MERMAID_GANTT_TEMPLATE: &str = r#"
        gantt
            title {{ title }}
            dateFormat {{ dateFormat }}
        {%- if axisFormat %}
            axisFormat {{ axisFormat }}
        {%- endif %}
    {%- for row in rows %}
        {%- if loop.changed(row.section) %}
            section {{ row.section }}
        {%- endif %}
                {{ row.task }}:{{ row.start }}, {{ row.end }}
    {%- endfor %}"#;

/// Mermaid.js gantt input jinja2 template
///
/// # Example
///
/// ```rust
/// use phymes_data::SubjectScript;
/// use phymes_data::MERMAID_GANTT_INPUT;
/// let inputs = serde_json::json!({
///     "title": "chart title",
///     "dateFormat": "X",
///     "axisFormat": "%s",
/// });
///
/// let input_string = SubjectScript::new_from_template(MERMAID_GANTT_INPUT.to_string()).apply_template(&inputs).unwrap()
///     .lines()
///     .map(|line| line.trim())
///     .collect::<Vec<&str>>()
///     .join("");
/// ```
pub static MERMAID_GANTT_INPUT: &str = r#"{
"title": "{{ title }}",
"dateFormat": "{{ dateFormat }}",
"axisFormat": "{{ axisFormat }}"
}"#;

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use crate::{MERMAID_HTML_POST, MERMAID_HTML_PRE, SubjectScript, TEMPLATE_TABLE_EXPRESSION};
    use anyhow::Result;
    use arrow::array::{ArrayRef, RecordBatch, StringArray, UInt32Array};
    use phymes_core::{
        BuildableTrait, BuilderTrait, MappableTrait, Subject, SubjectBuilderTrait, SubjectTrait,
    };
    use serde_json::{Map, Value};

    use super::*;

    #[test]
    fn test_mermaid_gantt_html() -> Result<()> {
        // Create the dummy data for the chart
        let section_vec = [
            "Section 1",
            "Section 1",
            "Section 1",
            "Section 2",
            "Section 2",
            "Section 2",
        ]
        .into_iter()
        .map(|s| s.to_string())
        .collect::<Vec<_>>();
        let task_vec = ["A", "B", "C", "D", "E", "F"]
            .into_iter()
            .map(|s| s.to_string())
            .collect::<Vec<_>>();
        let start_vec = [0, 1, 2, 0, 1, 2];
        let end_vec = [7, 8, 9, 10, 11, 12];

        let section_arr: ArrayRef = Arc::new(StringArray::from(section_vec));
        let task_arr: ArrayRef = Arc::new(StringArray::from(task_vec));
        let start_arr: ArrayRef = Arc::new(UInt32Array::from_iter_values(start_vec));
        let end_arr: ArrayRef = Arc::new(UInt32Array::from_iter_values(end_vec));
        let batch = RecordBatch::try_from_iter(vec![
            ("section", section_arr),
            ("task", task_arr),
            ("start", start_arr),
            ("end", end_arr),
        ])?;
        let table = Subject::get_builder()
            .with_name(TEMPLATE_TABLE_EXPRESSION)
            .with_record_batches(vec![batch])?
            .build()?;

        // Create the input for the template
        let inputs = serde_json::json!({
            "title": "chart title",
            "dateFormat": "X",
            "axisFormat": "%s"
        });
        let input_string = SubjectScript::new_from_template(MERMAID_GANTT_INPUT.to_string())
            .apply_template(&inputs)?
            .lines()
            .map(|line| line.trim())
            .collect::<Vec<&str>>()
            .join("");

        // Update the input with the dummy chart data
        let mut input_object = serde_json::from_str::<Map<String, Value>>(&input_string)?;
        let _ = input_object.insert(table.get_name().to_string(), table.to_json_object()?.into());
        let gantt_template_inputs = serde_json::to_value(input_object)?;

        // Create and render the template with the inputs
        let template = [MERMAID_HTML_PRE, MERMAID_GANTT_TEMPLATE, MERMAID_HTML_POST].join("");
        let script_string =
            SubjectScript::new_from_template(template).apply_template(&gantt_template_inputs)?;

        assert_eq!(
            script_string,
            "<!DOCTYPE html>\n<html>    \n    <head>\n        <meta http-equiv=\"Content-type\" content=\"text/html;charset=UTF-8\">\n        <meta name=\"color-scheme\" content=\"dark light\">\n        <style>\n            @media (prefers-color-scheme: dark) {\n                body {\n                    background-color: black;\n                    color: white;\n                }\n            }\n            @media (prefers-color-scheme: light) {\n                body {\n                    background-color: white;\n                    color: black;\n                }\n            }\n        </style>\n        <script type=\"module\">\n            import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';\n            mermaid.initialize({theme: \"dark\", startOnLoad: true });\n        </script>\n  </head>\n  <body>\n    <pre class=\"mermaid\">\n        gantt\n            title chart title\n            dateFormat X\n            axisFormat %s\n            section Section 1\n                A:0, 7\n                B:1, 8\n                C:2, 9\n            section Section 2\n                D:0, 10\n                E:1, 11\n                F:2, 12\n    </pre>\n  </body>\n</html>"
        );
        Ok(())
    }
}
