use anyhow::{Result, anyhow};
use clap::Parser;
use phymes_core::{MappableTrait, Table, TableTrait};
use phymes_data::DataConfigTrait;
use phymes_diagnostics::HashSet;
use serde::{Deserialize, Serialize};

use crate::candle_assets::AvailableCandleAssets;
use crate::openai_asset::AvailableOpenAIAssets;

/// Configuration for chat completion
///
/// # Notes
///
/// Not 100% OpenAI API compatible
/// see <https://platform.openai.com/docs/api-reference/chat/create> for differences
#[derive(Parser, Debug, Serialize, Deserialize, Default, Clone)]
#[command(author, version, about, long_about = None)]
pub struct CandleChatConfig {
    /// GGUF file to load, typically a .gguf file generated by the quantize command from llama.cpp
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights_file: Option<String>,

    /// The tokenizer config in json format.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_file: Option<String>,

    /// The model weights config in json format.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub weights_config_file: Option<String>,

    /// The tokenizer config config file in json format.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tokenizer_config_file: Option<String>,

    /// The API endpoint for chat completion
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_url: Option<String>,

    /// A list of messages comprising the conversation so far
    #[arg(long)]
    pub messages: String,

    /// A list of tools in JSON schema format
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tools: Option<String>,

    /// The length of the sample to generate (in tokens).
    #[arg(short = 'n', long, default_value_t = 1000)]
    pub max_tokens: usize,

    /// The temperature used to generate samples, use 0 for greedy sampling.
    #[arg(long, default_value_t = 0.8)]
    pub temperature: f64,

    /// Nucleus sampling probability cutoff.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,

    /// Only sample among the top K samples.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_k: Option<usize>,

    /// The seed to use when generating random samples.
    #[arg(long, default_value_t = 299792458)]
    pub seed: u64,

    /// Process prompt elements separately.
    #[arg(long)]
    pub split_prompt: bool,

    /// Run on CPU rather than GPU even if a GPU is available.
    #[arg(long)]
    pub cpu: bool,

    /// Penalty to be applied for repeating tokens, 1. means no penalty.
    #[arg(long, default_value_t = 1.1)]
    pub repeat_penalty: f32,

    /// The context size to consider for the repeat penalty.
    #[arg(long, default_value_t = 64)]
    pub repeat_last_n: usize,

    /// Number between -2.0 and 2.0.
    /// Positive values penalize new tokens based on their existing frequency in the text so far,
    /// decreasing the model's likelihood to repeat the same line verbatim
    #[arg(long, default_value_t = 0.0)]
    pub frequency_penalty: f32,

    /// The model to use.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub candle_asset: Option<AvailableCandleAssets>,

    /// The model to use.
    #[arg(long)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub openai_asset: Option<AvailableOpenAIAssets>,
}

impl DataConfigTrait for CandleChatConfig {
    fn to_example_json(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(&Self::default())
    }
    fn from_table(table: &Table) -> Result<Self>
    where
        Self: Sized,
    {
        // Check for the required fields
        let column_names = table
            .get_schema()
            .fields()
            .iter()
            .map(|f| f.name().to_string())
            .collect::<HashSet<_>>();
        if !((column_names.contains("candle_asset") || column_names.contains("openai_asset"))
            // && column_names.contains("max_tokens")
            // && column_names.contains("temperature")
            // && column_names.contains("seed")
            // && column_names.contains("repeat_penalty")
            // && column_names.contains("repeat_last_n")
            // && column_names.contains("frequency_penalty")
            && column_names.contains("messages"))
        {
            return Err(anyhow!(
                // "Table {} is missing required Field for `candle_asset`, `openai_asset`, `max_tokens`, `temperature`, `seed`, `repeat_penalty`, `repeat_last_n`, `messages`, or `frequency_penalty` in CandleChatConfig.",
                "Table {} is missing required Field for `candle_asset`, `openai_asset`, or `messages` in CandleChatConfig.",
                table.get_name()
            ));
        }

        // Try to build the config
        match table.to_struct::<CandleChatConfig>() {
            Ok(config_vec) => match config_vec.first() {
                Some(config) => Ok(config.to_owned()),
                None => Err(anyhow!(
                    "No config data found for CandleChatConfig with subject {}",
                    table.get_name()
                )),
            },
            Err(err) => Err(anyhow!(
                "CandleChatConfig could not be built for subject {}. {err}",
                table.get_name()
            )),
        }
    }
}
