name: guide

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

# trigger for all PRs and changes to main
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/**
      - phymes-book/**
      - phymes-app/**
      - phymes-subject/**
      - phymes-ml/**
      - phymes-data/**
      - phymes-network/**
      - phymes-server/**

jobs:
  book:
    name: Upload MDBook
    runs-on: self-hosted #ubuntu-latest
    container:
      image: amd64/rust
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Rust toolchain
        uses: ./.github/actions/rust-build-env
      - name: Test Book
        run: |
          mdbook test phymes-book
      # DM: Commented due to the following error...
      # ```
      # Unable to parse the input
      # WARN Error writing the RenderContext to the backend, Broken pipe (os error 32)
      # ERROR The "mermaid" preprocessor exited unsuccessfully with exit status: 1 status
      # ```
      # - name: Build Book
      #   run: |
      #     mdbook build phymes-book
      # - name: Setup Pages
      #   uses: actions/configure-pages@v4
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v4
      #   with:
      #     name: mdbook
      #     path: target/book
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
      #   with:
      #     artifact_name: mdbook

  docs:
    name: Upload cargo docs
    runs-on: self-hosted #ubuntu-latest
    container:
      image: amd64/rust
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Rust toolchain
        uses: ./.github/actions/rust-build-env
      - name: Run cargo doc
        run: |
          cargo doc --document-private-items --no-deps -p phymes-diagnostics
          cargo doc --document-private-items --no-deps -p phymes-subject
          cargo doc --document-private-items --no-deps -p phymes-ml
          cargo doc --document-private-items --no-deps -p phymes-data
          cargo doc --document-private-items --no-deps -p phymes-network
          cargo doc --document-private-items --no-deps -p phymes-server
          cargo doc --document-private-items --no-deps -p phymes-app
      - name: Fix file permissions for docs
        shell: sh
        run: |
          chmod -c -R +rX "target/doc" |
          while read line; do
              echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload cargo docs artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          name: crate-docs
          path: target/doc
